### ISSUE TITLE
hello friend, I love your project, I would like to contribute with some documentation, about privacy policies and contribution guidelines among others, that would be to add this information of not having it, what do you think the idea?

### ISSUE THREAD

**Issue by IntenselyMichell** [tckmn/semitone#11]
Hi. I found your project today while browsing the internet today. It is an incredible project and I am already putting it to use. I praise the incredible work you have done so far. I want to contribute to your project by creating some copies. That's documents of the privacy policy. For the declaration of the privacy policy, this is very necessary for the cases in which the data collection is carried out. I do not think it collects user information when using the software. However, I realized that the application has full network capabilities and things like that always make people skeptical. A concise statement of the privacy policy will put an end to all that skepticism, generating more confidence and leaving things clear. This document could be modified later as many times as necessary, it is only a beginning, but it would cover the most relevant aspects of privacy. Let you know what you think about this.

**Comment by tckmn** [comment]
Hello,

I'm not sure what you're talking about. Semitone [already has a privacy policy](https://tck.mn/semitone/privacy/), and it does not request network permissions or access the internet in any way.

**Comment by IntenselyMichell** [comment]
thank you friend for answering, I had not seen your privacy policy file, I was referring to something like this model:  <p><a href="https://github.com/brodeurlv/fastnfitness/blob/master/Privacy%20Policy.md">this File</a></p>

**Comment by IntenselyMichell** [comment]
in what refers to a contribution guide this would be a model, corrected by you and modified if necessary as many times as you wish, <a href="https://github.com/Dsiner/DMusic/blob/master/Contributing.md">this File</a>

**Comment by IntenselyMichell** [comment]
it is only documentation files that could be added and modified as you wish, it would be a free contribution, only with the interest of helping in the project

**Comment by tckmn** [comment]
Thank you for your offer, but I don't think this documentation is necessary at this time.
