### ISSUE TITLE
unable to open settings

### ISSUE THREAD

**Issue by aplufr** [tckmn/semitone#13]
On my phone when I click on the setting icon I get a menu with Settings and about.
On my tablet I does nothing. 
Both devices are running latest lineageos build 16.0 available and have the latest version of semitone from fdroid (1.2).
The tablet is a Samsung Galaxy S2 10".

**Comment by poppypundit** [comment]
Can't  open settings, app crashes.My  device is a Mediatek Helio X20.  Hope the tracker was closed because a fix was found. Commenting as no reply found.
