### ISSUE TITLE
App crashed when I clicked the about function

### ISSUE THREAD

**Issue by darewealth** [tckmn/semitone#15]
### Describe the bug.
When I clicked on the about, the app crashed

### Steps to reproduce.
* Launch the app.

* Click on settings icon down by the right 

* Then click about

* And see the error 

### Expected Behaviour
I was expecting to see the information about the app when I clicked the about feature in the app

### Screen recording.
https://youtu.be/Vt76cejyaO0

### Devices and Versions):)
* Device: [Gionee, M6]

* Version [8.1.0]

* App version [1.2]

**Comment by realrufans** [comment]
Worked well in version 1.1 but crashes in v1. 2

**Comment by tckmn** [comment]
this should hopefully be fixed in v1.3, which will be pushed to the play store and f-droid soon -- i'll leave this open for a while and close it if the crashes seem to have been fixed

**Comment by tckmn** [comment]
this seems to be fixed!
