### ISSUE TITLE
App crashed when I granted microphone permission on Android 8.1

### ISSUE THREAD

**Issue by darewealth** [tckmn/semitone#16]
### Describe the bug.
when I first launched the app, I tapped to grant microphone permission and the app crashed.

### Steps to reproduce.
* Launch the app.

* Tap on the info on the screen to grant microphone permission

* And see the error 

### Expected Behaviour
When I clicked to grant microphone permission, I expected the app launch successfully without crashing. 

### Screen recording.
https://youtu.be/wER5hp_ejBg

### Devices and Versions):)
* Device: [Gionee, M6]

* Version [8.1.0]

* App version [1.2]

**Additional information**
I reported this same issue on version 1.0 using Android 6.1 [here](https://github.com/tckmn/semitone/issues/4), which was rectified, but the same thing still occurs on the new version 1.2, using Android 8.1

**Comment by realrufans** [comment]
Same here. 
A lot of functions that works well in version 1.1 now crashes the app in version 1.2

**Comment by lawlit24** [comment]
men i have problem did you can help if you can 
I am working from a period on developing an application for an Android contact I've finished making the app But I had a problem i put all permissions i need for my apk like network and contact permissions in AndroidManifest.xml but when i install the apk in my phone the apk just open Without telling me to accept permissions Which i put Ie the phone has been rejected automatically what i do ??

**Comment by realrufans** [comment]
@lawlit24 make sure you're running on Android version 6 and later.

**Comment by lawlit24** [comment]
i test in my phone android version 7.0 api 24


Le ven. 31 mai 2019 à 08:21, solomon stephen <notifications@github.com> a
écrit :

**Comment by contrapunctus-1** [comment]
Same issue on Nokia 6.1, Android v9, v1.2 from F-Droid.

**Comment by andreymal** [comment]
Same (Xiaomi Redmi 4X, LineageOS 16 official)

**Comment by DSOTM-pf** [comment]
> men i have problem did you can help if you can
> I am working from a period on developing an application for an Android contact I've finished making the app But I had a problem i put all permissions i need for my apk like network and contact permissions in AndroidManifest.xml but when i install the apk in my phone the apk just open Without telling me to accept permissions Which i put Ie the phone has been rejected automatically what i do ??

Have you implemented runtime permission?  [runtime permission](https://developer.android.google.cn/training/permissions/requesting?hl=en)

**Comment by tckmn** [comment]
should hopefully be fixed in latest version -- see #15 for updates
