### ISSUE TITLE
App crashed when I exit the app using the phone back button

### ISSUE THREAD

**Issue by darewealth** [tckmn/semitone#17]
### Describe the bug
Anytime I click the phone back button to exit the app, the app crashed

### Steps to reproduce.
* Launch the app.

* Once you are in the app, click the phone back button to exit

* And see the error 

### Expected Behaviour
I expected the app to exit without the crashing

### Screen recording.
https://youtu.be/6uRsQ_641zI

### Devices and Versions):)
* Device: [Gionee, M6]

* Version [8.1.0]

* App version [1.2]

**Comment by contrapunctus-1** [comment]
Same issue on Nokia 6.1, Android v9, v1.2 from F-Droid.

**Comment by tckmn** [comment]
should hopefully be fixed in latest version -- see #15 for updates
