### ISSUE TITLE
Help: failed to build on Mac

### ISSUE THREAD

**Issue by yinxing2008** [tckmn/semitone#19]
I meet following error. And I found that "ffmpeg" under lib directory is empty.

$ tools/build_ffmpeg.sh
find: -printf: unknown primary or operator
head: head: illegal option -- z
usage: head [-n lines | -c bytes] [file ...]
illegal byte count -- -1

**Comment by tckmn** [comment]
if `lib/ffmpeg` is empty, you haven't downloaded the git submodules (clone with `--recurse-submodules` or run `git submodule update --init` after cloning)
